name: build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.14
      uses: actions/setup-node@v1
      with:
        node-version: '14.14'
    - name: Install yarn
      run: |
        yarn
      env:
        CI: true
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        GITHUB_USERNAME: mindsolutiondev
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: mindsolutiondev/authentication-api/authentication-api
        registry: docker.pkg.github.com
        username: mindsolutiondev
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile
        tags: latest
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: mindsolutiondev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: GITHUB_USERNAME, GITHUB_TOKEN
        script: |
          docker stop $(docker ps -aqf "ancestor=docker.pkg.github.com/mindsolutiondev/authentication-api/authentication-api:latest")
          docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
          docker pull docker.pkg.github.com/mindsolutiondev/authentication-api/authentication-api:latest
          docker run -dit -p 5001:5001 -d docker.pkg.github.com/mindsolutiondev/authentication-api/authentication-api:latest
